//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServices.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LifeSalesInfo
    {
        public Nullable<System.Guid> SalesGUID { get; set; }
        public string SalesName { get; set; }
        public string SalesReg { get; set; }
        public string SalesFC { get; set; }
        public string SalesInvest { get; set; }
        public string SalesQualID { get; set; }
        public string SalesMobIns { get; set; }
    }
}
